#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=installenv
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:25:00
#SBATCH --output=/home/jwiers/VLM-Grounding/MLX-Tests/LLAVA/job_outputs/install_env.out

module purge
module load 2022
module load Anaconda3/2022.05

conda create --name LLAVA python==3.8
source activate LLAVA
conda install pip
cd /home/jwiers/VLM-Grounding/MLX-Tests/LLAVA
pip install -r requirements.txt