#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=create_cogvlm_ans
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:25:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate fomo

# cd ../POPE

# srun python -u generate_cogvlm_answers.py --bf16

# srun python -u /gpfs/home6/rritter/VLM-Grounding/POPE/generate_cogvlm_answers.py --bf16

srun python -u /gpfs/home6/rritter/VLM-Grounding/POPE/generate_cogvlm_answers.py --bf16 --input_file /gpfs/home6/rritter/VLM-Grounding/POPE/output/coco/coco_box.json --output_file /gpfs/home6/rritter/VLM-Grounding/POPE/output/coco/ans/coco_box_ans.json

