#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=create_cogvlm_ans
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:25:00
#SBATCH --output=/home/jwiers/POPE/job_outputs/create_cogvlm_ans.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate cogvlm
cd ../POPE
srun python -u generate_cogvlm_answers.py --from_pretrained THUDM/cogvlm-chat-hf --bf16